# Generated by Django 5.1.1 on 2024-10-15 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='depID',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='staffID',
        ),
        migrations.RemoveField(
            model_name='department',
            name='staffID',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='staffID',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='depID',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='roomID',
        ),
        migrations.RemoveField(
            model_name='room',
            name='depID',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='doctorID',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='patientID',
        ),
        migrations.AddField(
            model_name='billing',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.department'),
        ),
        migrations.AddField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.patient'),
        ),
        migrations.AddField(
            model_name='billing',
            name='staff',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.staff'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='staff',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.staff'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.department'),
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HPApp.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.department'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.doctor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='patient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.patient'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='bill_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='specialization',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='General Medicine', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
