# Generated by Django 5.1.1 on 2024-10-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HPApp', '0003_user_remove_patient_m_name_staff_f_name_staff_l_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
