# Generated by Django 5.1.1 on 2024-10-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPApp', '0007_remove_user_role_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='patient', max_length=20),
        ),
    ]
