# Generated by Django 5.1.1 on 2024-10-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HPApp', '0010_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='department',
            name='staff',
        ),
    ]
