# Generated by Django 5.1.1 on 2024-10-27 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPApp', '0011_remove_department_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_type',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='staff',
        ),
        migrations.AddField(
            model_name='doctor',
            name='F_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='L_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HPApp.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
