# Generated by Django 5.1.1 on 2024-10-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HPApp', '0013_alter_user_options_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
