# Generated by Django 5.1.1 on 2024-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPApp', '0016_medicalrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='doctor_images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='doctor_images/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='doctor_images/'),
        ),
    ]
