# Generated by Django 5.1.1 on 2024-12-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPApp', '0018_timeinandoutdoctor_timeinandoutstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinandoutdoctor',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
